### ISSUE TITLE
Debug logs are not working

### ISSUE THREAD

**Issue by rcdailey** [linuxserver/docker-baseimage-alpine-nginx#39]
I took a peek at Alpine's way of [building nginx](https://git.alpinelinux.org/cgit/aports/tree/main/nginx/APKBUILD) and they do not seem to use `--with-debug`, which means `debug` severity in `error_log` does not work (reference [here](http://nginx.org/en/docs/debugging_log.html)).

For debugging reverse proxy issues, allowing debug logs is essential. The official nginx container works around this by providing an additional binary, named `nginx-debug`, to allow selecting the binary with debugging enabled.

Please allow debugging in nginx in some way.

**Comment by alex-phillips** [comment]
Unfortunately, this gets out of scope of what the container offers. The real problem is that alpine linux doesn't offer a build of nginx with debug included, so the only workaround would be 1 of two options: either we build nginx-debug when the image is created (which is a fairly involved process), or we bake in an `nginx-debug` binary. Either way, we would then be shipping a debug binary that would easily become out of date (either the binary itself or our build process) and it's not an official binary provided by the nginx team.

This could change if alpine linux included a debug binary in their package manager, but until then I think it's best that we don't try and ship it ourselves.

If you do need a debug version, I would suggest either building it inside the container yourself or getting ahold of the binary and simply copy it or mount it into your container via your run command.

**Comment by michalfapso** [comment]
I was trying to run nginx-debug inside SWAG and the following worked for me:
1.  My running SWAG container is named "swag". Copy a file from it `docker cp swag:/etc/s6-overlay/s6-rc.d/svc-nginx/run swag.s6.nginx.run`
2. Change the last line of `swag.s6.nginx.run` from `exec /usr/sbin/nginx` to `exec /usr/sbin/nginx-debug`.
3. Mount the file to the container in your docker-compose:
   ```
   services:
     swag:
       image: linuxserver/swag
       container_name: swag
       volumes:
         - ./swag.s6.nginx.run:/etc/s6-overlay/s6-rc.d/svc-nginx/run
   ...
   ```
4. Recreate the container: `docker-compose up -d --force-recreate swag`
5. Install `nginx-debug` package into the container: `docker exec -it swag apk add nginx-debug`
6. The s6 overlay running in the container should start it soon. You can check it with `docker exec -it swag ps ax | grep nginx`, you should see something like this:
   ```
     38 ?        S      0:00 s6-supervise svc-nginx
    855 ?        Ss     0:00 nginx: master process /usr/sbin/nginx-debug
    859 ?        S      0:00 nginx: worker process
    860 ?        S      0:00 nginx: worker process
    861 ?        S      0:00 nginx: cache manager process
   ```
7. When you finish debugging, don't forget to remove the mounted file from the step 3.

I'm not sure it's the correct way but it worked well for me.
